### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by ganxtah** [AEYCEN/QuickArmorSwap#2]
I set everything up perfectly, but for some reason when I hit my hot key I get this error message. What Can I do? Can you email me at txganxtah@gmail.com with a possible solution? I've tried joining the discord, but the invite is invalid.

     QuickArmorSwap v0.4-beta (30.04.24)
     © 2024 by AEYCEN / 2_L_8

     [OS: Windows 11 / Resolution: 2560x1440px]

     Enter your count of Amor sets(e.g. '5' or '10'): 2

     QuickArmorSwap is now RUNNING with the hotkey 'v'
     > Press '#' to deactivate QuickArmorSwap <
Exception in thread Thread-2 (process):
Traceback (most recent call last):
  File "C:\Users\Justin\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 1041, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "C:\Users\Justin\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Justin\Desktop\QuickArmorSwap-main\venv\Lib\site-packages\keyboard\_generic.py", line 58, in process
    if self.pre_process_event(event):
       ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Justin\Desktop\QuickArmorSwap-main\venv\Lib\site-packages\keyboard\__init__.py", line 218, in pre_process_event
    callback(event)
    ~~~~~~~~^^^^^^^
  File "C:\Users\Justin\Desktop\QuickArmorSwap-main\venv\Lib\site-packages\keyboard\__init__.py", line 649, in <lambda>
    handler = lambda e: (event_type == KEY_DOWN and e.event_type == KEY_UP and e.scan_code in _logically_pressed_keys) or (event_type == e.event_type and callback())

                                  ~~~~~~~~^^
  File "C:\Users\Justin\Desktop\QuickArmorSwap-main\run.py", line 249, in perform_macro
    displayText('Armor sets left: ' + str(set_count))
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Justin\Desktop\QuickArmorSwap-main\run.py", line 254, in displayText
    label = tkinter.Label(text=i_text, font=('OCR A Extended', font_size), fg='white', bg='black')
  File "C:\Users\Justin\AppData\Local\Programs\Python\Python313\Lib\tkinter\__init__.py", line 3361, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Justin\AppData\Local\Programs\Python\Python313\Lib\tkinter\__init__.py", line 2766, in __init__
    self._setup(master, cnf)
    ~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Justin\AppData\Local\Programs\Python\Python313\Lib\tkinter\__init__.py", line 2733, in _setup
    master = _get_default_root()
  File "C:\Users\Justin\AppData\Local\Programs\Python\Python313\Lib\tkinter\__init__.py", line 324, in _get_default_root
    root = Tk()
  File "C:\Users\Justin\AppData\Local\Programs\Python\Python313\Lib\tkinter\__init__.py", line 2459, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
              ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: Can't find a usable init.tcl in the following directories:
    C:/Users/Justin/AppData/Local/Programs/Python/Python313/lib/tcl8.6 C:/Users/Justin/AppData/Local/Programs/Python/lib/tcl8.6 C:/Users/Justin/AppData/Local/Programs/lib/tcl8.6 C:/Users/Justin/AppData/Local/Programs/Python/library C:/Users/Justin/AppData/Local/Programs/library C:/Users/Justin/AppData/Local/Programs/tcl8.6.14/library C:/Users/Justin/AppData/Local/tcl8.6.14/library



This probably means that Tcl wasn't installed properly.

**Comment by AEYCEN** [comment]
Successfully resolved on January 9th 2025
